## Populating_DB_Playgrounds:

In [5]:
import pandas as pd
import numpy as np
import psycopg2 
from sqlalchemy import create_engine, text
import warnings
warnings.filterwarnings("ignore")

from geopy.geocoders import Nominatim 
import time

In [21]:
# SQLAlchemy connection string format:
# postgresql+psycopg2://user:password@host:port/dbname
# Create engine and establish connection

DATABASE_URL = (
    "postgresql+psycopg2://neondb_owner:npg_CeS9fJg2azZD"
    "@ep-falling-glitter-a5m0j5gk-pooler.us-east-2.aws.neon.tech:5432/neondb"
    "?sslmode=require"
)


engine = create_engine(DATABASE_URL)

In [22]:
## Creating a new table:

with engine.begin() as conn:
    conn.execute(text("""
    CREATE TABLE IF NOT EXISTS test_berlin_data.playgrounds (
    technical_id VARCHAR(100) UNIQUE NOT NULL,
    key VARCHAR(50) UNIQUE NOT NULL,
    object_number VARCHAR(100),
    district  VARCHAR(100) NOT NULL, 
    neighborhood  VARCHAR(100),
    green_area_type VARCHAR(100),
    playground_name VARCHAR(100) , 
    playground_suffix  VARCHAR(100), 
    year_built FLOAT,
    last_renovation_year FLOAT, 
    area_sqm FLOAT,
    dedication VARCHAR(100),
    planning_area_number FLOAT, 
    planning_area_name VARCHAR(100), 
    net_play_area_sqm FLOAT,
    full_address VARCHAR(200),
    latitude DECIMAL(9,6),
    longitude DECIMAL(9,6),
    FOREIGN KEY (district) REFERENCES test_berlin_data.neighborhood(neighborhood) ON DELETE RESTRICT ON UPDATE CASCADE
    )

"""))

In [17]:
df=pd.read_csv('../sources/playground_transformed.csv')

df.head()

,technical_id,key,object_number,district,neighborhood,green_area_type,playground_name,playground_suffix,year_built,last_renovation_year,area_sqm,dedication,planning_area_number,planning_area_name,net_play_area_sqm,full_address,latitude,longitude
0,00008100_002f2c6b,00008100:002f2c6b,19441,Tempelhof-Schöneberg,Lichtenrade,Spielplatz,Nuthestr. 26,Unknown,NaN,NaN,NaN,Unknown,NaN,Unknown,NaN,"Nuthestr. 26,-, Berlin, Germany",52.393914,13.394292
1,00008100_0033cfac,00008100:0033cfac,35098,Reinickendorf,Tegel,Spielplatz,Borsigdamm 4 (Spielplatz),Unknown,NaN,NaN,5031.9,Unknown,12200413.0,Tegel Süd,NaN,"Borsigdamm 4 (Spielplatz),Tegel Süd, Berlin, G...",NaN,NaN
2,00008100_0032a99a,00008100:0032a99a,21AS10,Lichtenberg,Lichtenberg,Spielplatz,Gudrunstr. 14 Spielplatz,Unknown,NaN,NaN,713.0,gewidmet,11300725.0,Nibelungenviertel,NaN,"Gudrunstr. 14 Spielplatz,Nibelungenviertel, Be...",NaN,NaN
3,00008100_00199411,00008100:00199411,00156,Marzahn-Hellersdorf,Marzahn,Spielplatz,Hohenwalder/Schorfheider Straße -Dreieck,seit 1990 pädagog. betreuter Spielplatz,1988.0,NaN,3934.0,gewidmet,10100104.0,Golliner Straße,NaN,"Hohenwalder/Schorfheider Straße -Dreieck,Golli...",NaN,NaN
4,00008100_00281623,00008100:00281623,150072,Treptow-Köpenick,Schmöckwitz,Spielplatz,Biebersdorfer Weg 12/ Lübbenauer Weg 23 Sch KSP,Unknown,NaN,NaN,900.0,gewidmet,9301227.0,Karolinenhof,NaN,Biebersdorfer Weg 12/ Lübbenauer Weg 23 Sch KS...,NaN,NaN

In [18]:
df['district'].nunique()

12

In [23]:
df.to_sql(name="playgrounds",
         con=engine,
         schema="test_berlin_data",
         if_exists= "append",
         index = False)

879