In [3]:
import sys
import os

# Simple path fix - go up one level to data_loader directory
sys.path.append('../')

print(f"Added parent directory to path")
print(f"Current working directory: {os.getcwd()}")

Added parent directory to path
Current working directory: /Users/svitlanakovalivska/layered-populate-data-pool-da/db_population_utils/data_loader/test

In [4]:
# Import the SmartAutoDataLoader and test CSV loading
from smart_auto_data_loader import SmartAutoDataLoader
df = loader.load("/Users/svitlanakovalivska/layered-populate-data-pool-da/db_population_utils/data/test.csv")

NameError: name 'loader' is not defined

In [ ]:
df

,id,keyword,location,text
0,0,NaN,NaN,Just happened a terrible car crash
1,2,NaN,NaN,"Heard about #earthquake is different cities, s..."
2,3,NaN,NaN,"there is a forest fire at spot pond, geese are..."
3,9,NaN,NaN,Apocalypse lighting. #Spokane #wildfires
4,11,NaN,NaN,Typhoon Soudelor kills 28 in China and Taiwan
...,...,...,...,...
3258,10861,NaN,NaN,EARTHQUAKE SAFETY LOS ANGELES ¬â√õ√í SAFETY FASTE...
3259,10865,NaN,NaN,Storm in RI worse than last hurricane. My city...
3260,10868,NaN,NaN,Green Line derailment in Chicago http://t.co/U...
3261,10874,NaN,NaN,MEG issues Hazardous Weather Outlook (HWO) htt...
3262,10875,NaN,NaN,#CityofCalgary has activated its Municipal Eme...

In [ ]:
# Cell 1: Install dependencies
!pip install openpyxl xlrd
print("üì¶ Excel support installed!")


# Cell 4: Test Excel
import importlib
import smart_auto_data_loader
importlib.reload(smart_auto_data_loader)

from smart_auto_data_loader import SmartAutoDataLoader

loader = SmartAutoDataLoader(verbose=True)
df = loader.load("/Users/svitlanakovalivska/layered-populate-data-pool-da/db_population_utils/data/statistischer-bericht-auslaend-bevoelkerung-2010200247005.xlsx")

Requirement already satisfied: openpyxl in /Users/svitlanakovalivska/layered-populate-data-pool-da/.conda/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: xlrd in /Users/svitlanakovalivska/layered-populate-data-pool-da/.conda/lib/python3.12/site-packages (2.0.2)
Requirement already satisfied: et-xmlfile in /Users/svitlanakovalivska/layered-populate-data-pool-da/.conda/lib/python3.12/site-packages (from openpyxl) (2.0.0)
üì¶ Excel support installed!
üéØ SmartAutoDataLoader ready!
üéØ Loading file: statistischer-bericht-auslaend-bevoelkerung-2010200247005.xlsx
üîç Format detected: excel
üìà Loading Excel file...
   üìã Available sheets: ['Titel', 'Inhalts√ºbersicht', 'GENESIS-Online', 'Impressum', 'Informationen zur Statistik', '12521-01', '12521-02', '12521-03', '12521-04', '12521-05', '12521-06', '12521-07', '12521-08', '12521-09', '12521-10', '12521-11', '12521-12', '12521-13', '12521-14', '12521-15', '12521-16', 'Erl√§uterung_zu_CSV-Tabellen', 'csv-12521-01', 'csv-12521-02', 'csv-12521-03', 'csv-12521-04', 'csv-12521-05', 'csv-12521-06', 'csv-12521-07', 'csv-12521-08', 'csv-12521-09', 'csv-12521-10', 'csv-12521-11', 'csv-12521-12', 'csv-12521-13', 'csv-12521-14', 'csv-12521-15', 'csv-12521-16']
   ‚úÖ Selected sheet: 'csv-12521-15'
üóìÔ∏è Searching for date columns...
   ‚úÖ Found date column: 'Stichtag' (%d.%m.%Y)
   üìÖ Total date columns found: 1
‚úÖ Excel loaded: 1309 rows, 24 columns
   üìä Column names: ['Statistik_Code', 'Statistik_Label', 'Stichtag', 'Region', 'AGS_Kreis', 'Geschlecht', 'Bestand_am_31_12_2023_Anzahl', 'Zugaenge_in_2024_Insgesamt_Anzahl', 'Erstzuzug_aus_dem_Ausland_in_2024_Anzahl', 'Wiederzuzug_aus_dem_Ausland_in_2024_Anzahl', 'Geburten_in_2024_Anzahl', 'Zuzug_im_Inland_in_2024_Anzahl', 'Abgaenge_in_2024_Insgesamt_Anzahl', 'Fortzuege_ins_Ausland_in_2024_Anzahl', 'Abmeldungen_ins_Ausland_in_2024_Anzahl', 'Tod_in_2024_Anzahl', 'Registerloeschung_in_2024_Anzahl', 'Fortzug_im_Inland_in_2024_Anzahl', 'Geburtenueberschuss_in_2024_Anzahl', 'Nettozuwanderung_aus_Ausland_in_2024_Anzahl', 'Nettozuwanderung_aus_Inland_in_2024_Anzahl', 'Bestand_am_31_12_2024_Anzahl', 'Nachrichtlich_Zugaenge_in_2024_Anzahl', 'Nachrichtlich_Abgaenge_in_2024_Anzahl']

In [ ]:
df

,Statistik_Code,Statistik_Label,Stichtag,Region,AGS_Kreis,Geschlecht,Bestand_am_31_12_2023_Anzahl,Zugaenge_in_2024_Insgesamt_Anzahl,Erstzuzug_aus_dem_Ausland_in_2024_Anzahl,Wiederzuzug_aus_dem_Ausland_in_2024_Anzahl,...,Abmeldungen_ins_Ausland_in_2024_Anzahl,Tod_in_2024_Anzahl,Registerloeschung_in_2024_Anzahl,Fortzug_im_Inland_in_2024_Anzahl,Geburtenueberschuss_in_2024_Anzahl,Nettozuwanderung_aus_Ausland_in_2024_Anzahl,Nettozuwanderung_aus_Inland_in_2024_Anzahl,Bestand_am_31_12_2024_Anzahl,Nachrichtlich_Zugaenge_in_2024_Anzahl,Nachrichtlich_Abgaenge_in_2024_Anzahl
0,12521,Auslaenderstatistik,2024-12-31,Deutschland ...,Kein_AGS ...,Insgesamt,13895865.0,1285655.0,972850.0,205350.0,...,324415.0,46605,354780.0,.,60850.0,459705.0,.,14061640.0,226800.0,225380.0
1,12521,Auslaenderstatistik,2024-12-31,Deutschland ...,Kein_AGS ...,Maennlich,7305105.0,728825.0,539235.0,134420.0,...,219910.0,27440,188065.0,.,27725.0,232455.0,.,7377225.0,128280.0,138090.0
2,12521,Auslaenderstatistik,2024-12-31,Deutschland ...,Kein_AGS ...,Weiblich,6590755.0,556835.0,433610.0,70930.0,...,104505.0,19160,166720.0,.,33130.0,227245.0,.,6684415.0,98520.0,87290.0
3,12521,Auslaenderstatistik,2024-12-31,Schleswig-Holstein ...,Kein_AGS ...,Insgesamt,346690.0,54800.0,28625.0,4835.0,...,9155.0,970,10830.0,19485,2115.0,13920.0,-1235,350665.0,5540.0,7140.0
4,12521,Auslaenderstatistik,2024-12-31,Schleswig-Holstein ...,Kein_AGS ...,Maennlich,181985.0,31310.0,15835.0,3115.0,...,6250.0,525,5845.0,11215,1070.0,7030.0,-450,183790.0,3095.0,4370.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,12521,Auslaenderstatistik,2024-12-31,Greiz ...,16076 ...,Weiblich,2035.0,385.0,235.0,50.0,...,90.0,5,5.0,125,20.0,110.0,-50,2110.0,20.0,50.0
1305,12521,Auslaenderstatistik,2024-12-31,Altenburger_Land ...,16077 ...,Insgesamt,6750.0,1695.0,1225.0,90.0,...,130.0,10,125.0,355,60.0,905.0,-50,7545.0,120.0,55.0
1306,12521,Auslaenderstatistik,2024-12-31,Altenburger_Land ...,16077 ...,Maennlich,3530.0,855.0,590.0,50.0,...,85.0,5,70.0,220,20.0,395.0,-30,3845.0,55.0,45.0
1307,12521,Auslaenderstatistik,2024-12-31,Altenburger_Land ...,16077 ...,Weiblich,3220.0,840.0,640.0,35.0,...,45.0,5,55.0,140,40.0,515.0,-25,3700.0,65.0,10.0
1308,Ende der Tabelle.,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN