In [ ]:
pip install googlemaps

Requirement already satisfied: googlemaps in /usr/local/lib/python3.11/dist-packages (4.10.0)
Requirement already satisfied: requests<3.0,>=2.20.0 in /usr/local/lib/python3.11/dist-packages (from googlemaps) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2025.8.3)

In [ ]:
import pandas as pd
import googlemaps
import time

# Load your CSV file into a DataFrame
df = pd.read_csv('universities_berlin_rating_final.csv')

# Initialize the Google Maps client with your API key
gmaps = googlemaps.Client(key='Insert Google Key Number here')

# Function to geocode an address using Google Maps Geocoding API
def geocode_address(address):
    try:
        geocode_result = gmaps.geocode(address)
        if geocode_result:
            location = geocode_result[0]['geometry']['location']
            postcode = next((addr['long_name'] for addr in geocode_result[0]['address_components'] if 'postal_code' in addr['types']), None)
            neighborhood = next((addr['long_name'] for addr in geocode_result[0]['address_components'] if 'neighborhood' in addr['types']), None)
            return {
                'latitude': location['lat'],
                'longitude': location['lng'],
                'postcode': postcode,
                'neighborhood': neighborhood
            }
    except Exception as e:
        print(f"Error geocoding {address}: {e}")
    return None

# Add new columns for geolocation data
df['latitude'] = None
df['longitude'] = None
df['postcode'] = None
df['neighborhood'] = None

# Iterate over the DataFrame and geocode each university
for index, row in df.iterrows():
    university_name = row['University Name']
    address = f"{university_name}, Berlin, Germany"
    result = geocode_address(address)
    if result:
        df.at[index, 'latitude'] = result.get('latitude')
        df.at[index, 'longitude'] = result.get('longitude')
        df.at[index, 'postcode'] = result.get('postcode')
        df.at[index, 'neighborhood'] = result.get('neighborhood')
    time.sleep(1)  # Rate limiting: wait for 1 second between requests

# Save the updated DataFrame to a new CSV file
df.to_csv('universities_berlin_rating_final_with_geolocation.csv', index=False)

In [ ]:
df=pd.read_csv('universities_berlin_rating_final_with_geolocation.csv')
df.head(30)

,University Name,Rank in Berlin-Brandenburg,Rank in Germany,latitude,longitude,postcode,neighborhood
0,1. Free University of Berlin,1,5,52.454324,13.293477,14195.0,NaN
1,2. Humboldt University of Berlin,2,8,52.517883,13.393655,10117.0,NaN
2,3. Technical University of Berlin,3,19,52.512532,13.326945,10623.0,NaN
3,4. Charite - Medical University of Berlin,4,21,52.469383,13.311426,14197.0,NaN
4,5. Berlin University of Applied Sciences,7,84,52.515796,13.328141,10587.0,NaN
5,6. Berlin School of Economics and Law,9,92,52.485406,13.337745,10825.0,NaN
6,7. Berlin Technical University of Applied Scie...,10,95,52.512532,13.326945,10623.0,NaN
7,8. Berlin University of the Arts,11,98,52.509243,13.326963,10623.0,NaN
8,9. Hertie School of Governance,12,100,52.512791,13.389224,10117.0,NaN
9,10. Steinbeis University,15,135,52.429987,13.529880,12489.0,NaN
10,11. ESMT Berlin,16,153,52.515649,13.401151,10178.0,NaN
11,12. Bard College Berlin,17,171,52.584304,13.393721,13156.0,NaN
12,13. SRH University of Applied Sciences Berlin,18,180,52.474552,13.457486,12059.0,NaN
13,14. University of Performing Arts Ernst Busch,19,190,52.532390,13.383218,10115.0,NaN
14,15. International Psychoanalytic University,20,194,52.523578,13.342548,10555.0,NaN
15,16. Psychological Institute in Berlin,21,201,52.520007,13.404954,NaN,NaN
16,17. Alice Salomon University of Applied Scienc...,24,215,52.537567,13.606320,12627.0,NaN
17,18. Berlin-Weissensee Art Academy,25,222,52.558034,13.439384,13086.0,NaN
18,19. Hanns Eisler Academy of Music,26,240,52.516584,13.403371,10178.0,NaN
19,20. German University for Professional Studies,28,276,52.500166,13.292532,10711.0,NaN
20,21. Mediadesign University of Applied Social S...,29,303,52.488459,13.533344,10318.0,NaN
21,22. Quadriga University of Applied Social Scie...,30,304,52.515146,13.397365,10117.0,NaN
22,"23. University of Applied Sciences for Media, ...",32,312,52.520007,13.404954,NaN,NaN
23,24. Catholic University of Applied Social Scie...,33,313,52.488459,13.533344,10318.0,NaN
24,"25. University of Applied Sciences, Berlin",34,315,52.544653,13.352809,13353.0,NaN
25,26. Protestant University of Applied Sciences ...,35,316,52.423268,13.261658,14167.0,NaN
26,27. H:G College of Health and Sports,36,329,52.520007,13.404954,NaN,NaN
27,28. MSB Medical School Berlin,37,330,52.469383,13.311426,14197.0,NaN
28,29. BSP Business School Berlin,38,332,52.438743,13.328609,12247.0,NaN
29,30. bbw University of Applied Sciences,39,338,52.435780,13.537809,12489.0,NaN

In [ ]:
pip install googlemaps

Requirement already satisfied: googlemaps in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (4.10.0)
Requirement already satisfied: requests<3.0,>=2.20.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from googlemaps) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests<3.0,>=2.20.0->googlemaps) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests<3.0,>=2.20.0->googlemaps) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests<3.0,>=2.20.0->googlemaps) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests<3.0,>=2.20.0->googlemaps) (2025.1.31)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd
import googlemaps
import time

# Load your CSV file into a DataFrame
df = pd.read_csv('universities_berlin_rating_final_with_geolocation.csv')

# Initialize the Google Maps client
gmaps = googlemaps.Client(key='Google Key Number')

# Function to perform reverse geocoding and extract neighborhood information
def get_neighborhood(lat, lng):
    try:
        reverse_geocode_result = gmaps.reverse_geocode((lat, lng))
        for result in reverse_geocode_result:
            for component in result['address_components']:
                if 'sublocality_level_1' in component['types']:
                    return component['long_name']
        return None
    except Exception as e:
        print(f"Error in reverse geocoding: {e}")
        return None

# Apply the reverse geocoding function to each row
df['neighborhood'] = df.apply(lambda row: get_neighborhood(row['latitude'], row['longitude']), axis=1)

# Save the updated DataFrame to a new CSV file
df.to_csv('universities_Berlin_full_info.csv', index=False)

# Display the updated DataFrame
print("Final DataFrame with neighborhood information:")
print(df)

Final DataFrame with neighborhood information:
                                      University Name  \
0                        1. Free University of Berlin
1                    2. Humboldt University of Berlin
2                   3. Technical University of Berlin
3           4. Charite - Medical University of Berlin
4            5. Berlin University of Applied Sciences
5               6. Berlin School of Economics and Law
6   7. Berlin Technical University of Applied Scie...
7                    8. Berlin University of the Arts
8                      9. Hertie School of Governance
9                            10. Steinbeis University
10                                    11. ESMT Berlin
11                            12. Bard College Berlin
12      13. SRH University of Applied Sciences Berlin
13      14. University of Performing Arts Ernst Busch
14        15. International Psychoanalytic University
15              16. Psychological Institute in Berlin
16  17. Alice Salomon University of Applied Scienc...
17                  18. Berlin-Weissensee Art Academy
18                  19. Hanns Eisler Academy of Music
19     20. German University for Professional Studies
20  21. Mediadesign University of Applied Social S...
21  22. Quadriga University of Applied Social Scie...
22  23. University of Applied Sciences for Media, ...
23  24. Catholic University of Applied Social Scie...
24         25. University of Applied Sciences, Berlin
25  26. Protestant University of Applied Sciences ...
26               27. H:G College of Health and Sports
27                      28. MSB Medical School Berlin
28                     29. BSP Business School Berlin
29             30. bbw University of Applied Sciences
30  31. ESMOD International University of Art for ...
31  32. VICTORIA, International University of Appl...
32           33. DEKRA University of Applied Sciences
33                34. Akkon College of Human Sciences
34  35. IB University of Applied Social Sciences B...
35                           36. Touro College Berlin

    Rank in Berlin-Brandenburg  Rank in Germany   latitude  longitude  \
0                            1                5  52.454324  13.293477
1                            2                8  52.517883  13.393655
2                            3               19  52.512532  13.326945
3                            4               21  52.469383  13.311426
4                            7               84  52.515796  13.328141
5                            9               92  52.485406  13.337745
6                           10               95  52.512532  13.326945
7                           11               98  52.509243  13.326963
8                           12              100  52.512791  13.389224
9                           15              135  52.429987  13.529880
10                          16              153  52.515649  13.401151
11                          17              171  52.584304  13.393721
12                          18              180  52.474552  13.457486
13                          19              190  52.532390  13.383218
14                          20              194  52.523578  13.342548
15                          21              201  52.520007  13.404954
16                          24              215  52.537567  13.606320
17                          25              222  52.558034  13.439384
18                          26              240  52.516584  13.403371
19                          28              276  52.500166  13.292532
20                          29              303  52.488459  13.533344
21                          30              304  52.515146  13.397365
22                          32              312  52.520007  13.404954
23                          33              313  52.488459  13.533344
24                          34              315  52.544653  13.352809
25                          35              316  52.423268  13.261658
26                          36              329  52.520007  13.404954
27                          37              330  52.469383  13.311426
28                          38              332  52.438743  13.328609
29                          39              338  52.435780  13.537809
30                          40              341  52.497665  13.440150
31                          41              343  52.505199  13.378054
32                          42              345  52.515796  13.328141
33                          43              346  52.520007  13.404954
34                          44              349  52.506407  13.365078
35                          45              359  52.505167  13.213509

    postcode                       neighborhood
0    14195.0         Bezirk Steglitz-Zehlendorf
1    10117.0                              Mitte
2    10623.0  Bezirk Charlottenburg-Wilmersdorf
3    14197.0  Bezirk Charlottenburg-Wilmersdorf
4    10587.0  Bezirk Charlottenburg-Wilmersdorf
5    10825.0        Bezirk Tempelhof-Schöneberg
6    10623.0  Bezirk Charlottenburg-Wilmersdorf
7    10623.0  Bezirk Charlottenburg-Wilmersdorf
8    10117.0                              Mitte
9    12489.0            Bezirk Treptow-Köpenick
10   10178.0                              Mitte
11   13156.0                      Bezirk Pankow
12   12059.0                    Bezirk Neukölln
13   10115.0                              Mitte
14   10555.0                              Mitte
15       NaN                              Mitte
16   12627.0         Bezirk Marzahn-Hellersdorf
17   13086.0                      Bezirk Pankow
18   10178.0                              Mitte
19   10711.0  Bezirk Charlottenburg-Wilmersdorf
20   10318.0                 Bezirk Lichtenberg
21   10117.0                              Mitte
22       NaN                              Mitte
23   10318.0                 Bezirk Lichtenberg
24   13353.0                              Mitte
25   14167.0         Bezirk Steglitz-Zehlendorf
26       NaN                              Mitte
27   14197.0  Bezirk Charlottenburg-Wilmersdorf
28   12247.0         Bezirk Steglitz-Zehlendorf
29   12489.0            Bezirk Treptow-Köpenick
30   10997.0    Bezirk Friedrichshain-Kreuzberg
31   10963.0    Bezirk Friedrichshain-Kreuzberg
32   10587.0  Bezirk Charlottenburg-Wilmersdorf
33       NaN                              Mitte
34   10785.0                              Mitte
35   14055.0  Bezirk Charlottenburg-Wilmersdorf

In [ ]:
import pandas as pd

# Load the CSV file into a DataFrame
df = pd.read_csv('universities_Berlin_full_info.csv')

# Remove the word "Bezirk" from the neighborhood column
df['neighborhood'] = df['neighborhood'].str.replace('Bezirk ', '', regex=False)

# Save the updated DataFrame to a new CSV file
df.to_csv('universities_Berlin_full_info_clean.csv', index=False)

# Display the updated DataFrame
print("Final DataFrame with cleaned neighborhood information:")
print(df)

Final DataFrame with cleaned neighborhood information:
                                      University Name  \
0                        1. Free University of Berlin
1                    2. Humboldt University of Berlin
2                   3. Technical University of Berlin
3           4. Charite - Medical University of Berlin
4            5. Berlin University of Applied Sciences
5               6. Berlin School of Economics and Law
6   7. Berlin Technical University of Applied Scie...
7                    8. Berlin University of the Arts
8                      9. Hertie School of Governance
9                            10. Steinbeis University
10                                    11. ESMT Berlin
11                            12. Bard College Berlin
12      13. SRH University of Applied Sciences Berlin
13      14. University of Performing Arts Ernst Busch
14        15. International Psychoanalytic University
15              16. Psychological Institute in Berlin
16  17. Alice Salomon University of Applied Scienc...
17                  18. Berlin-Weissensee Art Academy
18                  19. Hanns Eisler Academy of Music
19     20. German University for Professional Studies
20  21. Mediadesign University of Applied Social S...
21  22. Quadriga University of Applied Social Scie...
22  23. University of Applied Sciences for Media, ...
23  24. Catholic University of Applied Social Scie...
24         25. University of Applied Sciences, Berlin
25  26. Protestant University of Applied Sciences ...
26               27. H:G College of Health and Sports
27                      28. MSB Medical School Berlin
28                     29. BSP Business School Berlin
29             30. bbw University of Applied Sciences
30  31. ESMOD International University of Art for ...
31  32. VICTORIA, International University of Appl...
32           33. DEKRA University of Applied Sciences
33                34. Akkon College of Human Sciences
34  35. IB University of Applied Social Sciences B...
35                           36. Touro College Berlin

    Rank in Berlin-Brandenburg  Rank in Germany   latitude  longitude  \
0                            1                5  52.454324  13.293477
1                            2                8  52.517883  13.393655
2                            3               19  52.512532  13.326945
3                            4               21  52.469383  13.311426
4                            7               84  52.515796  13.328141
5                            9               92  52.485406  13.337745
6                           10               95  52.512532  13.326945
7                           11               98  52.509243  13.326963
8                           12              100  52.512791  13.389224
9                           15              135  52.429987  13.529880
10                          16              153  52.515649  13.401151
11                          17              171  52.584304  13.393721
12                          18              180  52.474552  13.457486
13                          19              190  52.532390  13.383218
14                          20              194  52.523578  13.342548
15                          21              201  52.520007  13.404954
16                          24              215  52.537567  13.606320
17                          25              222  52.558034  13.439384
18                          26              240  52.516584  13.403371
19                          28              276  52.500166  13.292532
20                          29              303  52.488459  13.533344
21                          30              304  52.515146  13.397365
22                          32              312  52.520007  13.404954
23                          33              313  52.488459  13.533344
24                          34              315  52.544653  13.352809
25                          35              316  52.423268  13.261658
26                          36              329  52.520007  13.404954
27                          37              330  52.469383  13.311426
28                          38              332  52.438743  13.328609
29                          39              338  52.435780  13.537809
30                          40              341  52.497665  13.440150
31                          41              343  52.505199  13.378054
32                          42              345  52.515796  13.328141
33                          43              346  52.520007  13.404954
34                          44              349  52.506407  13.365078
35                          45              359  52.505167  13.213509

    postcode                neighborhood
0    14195.0         Steglitz-Zehlendorf
1    10117.0                       Mitte
2    10623.0  Charlottenburg-Wilmersdorf
3    14197.0  Charlottenburg-Wilmersdorf
4    10587.0  Charlottenburg-Wilmersdorf
5    10825.0        Tempelhof-Schöneberg
6    10623.0  Charlottenburg-Wilmersdorf
7    10623.0  Charlottenburg-Wilmersdorf
8    10117.0                       Mitte
9    12489.0            Treptow-Köpenick
10   10178.0                       Mitte
11   13156.0                      Pankow
12   12059.0                    Neukölln
13   10115.0                       Mitte
14   10555.0                       Mitte
15       NaN                       Mitte
16   12627.0         Marzahn-Hellersdorf
17   13086.0                      Pankow
18   10178.0                       Mitte
19   10711.0  Charlottenburg-Wilmersdorf
20   10318.0                 Lichtenberg
21   10117.0                       Mitte
22       NaN                       Mitte
23   10318.0                 Lichtenberg
24   13353.0                       Mitte
25   14167.0         Steglitz-Zehlendorf
26       NaN                       Mitte
27   14197.0  Charlottenburg-Wilmersdorf
28   12247.0         Steglitz-Zehlendorf
29   12489.0            Treptow-Köpenick
30   10997.0    Friedrichshain-Kreuzberg
31   10963.0    Friedrichshain-Kreuzberg
32   10587.0  Charlottenburg-Wilmersdorf
33       NaN                       Mitte
34   10785.0                       Mitte
35   14055.0  Charlottenburg-Wilmersdorf

In [ ]:
import pandas as pd

# Load your CSV file into a DataFrame
df = pd.read_csv('universities_Berlin_full_info_clean.csv')

# Mapping of neighborhoods to AGS codes
ags_mapping = {
    'Mitte': '11000001',
    'Friedrichshain-Kreuzberg': '11000002',
    'Pankow': '11000003',
    'Charlottenburg-Wilmersdorf': '11000004',
    'Spandau': '11000005',
    'Steglitz-Zehlendorf': '11000006',
    'Tempelhof-Schöneberg': '11000007',
    'Neukölln': '11000008',
    'Treptow-Köpenick': '11000009',
    'Marzahn-Hellersdorf': '11000010',
    'Lichtenberg': '11000011',
    'Reinickendorf': '11000012'
}

# Function to get AGS code from neighborhood
def get_ags_code(neighborhood):
    return ags_mapping.get(neighborhood, None)

# Apply the function to get AGS code
df['AGS_Code'] = df['neighborhood'].apply(get_ags_code)

# Ensure AGS_Code is a string type
df['AGS_Code'] = df['AGS_Code'].astype(str)

# Transform postcode to string and remove trailing zeros and decimal points
if 'postcode' in df.columns:
    df['postcode'] = df['postcode'].astype(str).str.replace(r'\.0$', '', regex=True)

# Save the updated DataFrame to a new CSV file
df.to_csv('universities_Berlin_final.csv', index=False)

# Display the updated DataFrame
print("Final DataFrame with AGS code and cleaned postcode information:")
print(df)

Final DataFrame with AGS code and cleaned postcode information:
                                      University Name  \
0                        1. Free University of Berlin
1                    2. Humboldt University of Berlin
2                   3. Technical University of Berlin
3           4. Charite - Medical University of Berlin
4            5. Berlin University of Applied Sciences
5               6. Berlin School of Economics and Law
6   7. Berlin Technical University of Applied Scie...
7                    8. Berlin University of the Arts
8                      9. Hertie School of Governance
9                            10. Steinbeis University
10                                    11. ESMT Berlin
11                            12. Bard College Berlin
12      13. SRH University of Applied Sciences Berlin
13      14. University of Performing Arts Ernst Busch
14        15. International Psychoanalytic University
15              16. Psychological Institute in Berlin
16  17. Alice Salomon University of Applied Scienc...
17                  18. Berlin-Weissensee Art Academy
18                  19. Hanns Eisler Academy of Music
19     20. German University for Professional Studies
20  21. Mediadesign University of Applied Social S...
21  22. Quadriga University of Applied Social Scie...
22  23. University of Applied Sciences for Media, ...
23  24. Catholic University of Applied Social Scie...
24         25. University of Applied Sciences, Berlin
25  26. Protestant University of Applied Sciences ...
26               27. H:G College of Health and Sports
27                      28. MSB Medical School Berlin
28                     29. BSP Business School Berlin
29             30. bbw University of Applied Sciences
30  31. ESMOD International University of Art for ...
31  32. VICTORIA, International University of Appl...
32           33. DEKRA University of Applied Sciences
33                34. Akkon College of Human Sciences
34  35. IB University of Applied Social Sciences B...
35                           36. Touro College Berlin

    Rank in Berlin-Brandenburg  Rank in Germany   latitude  longitude  \
0                            1                5  52.454324  13.293477
1                            2                8  52.517883  13.393655
2                            3               19  52.512532  13.326945
3                            4               21  52.469383  13.311426
4                            7               84  52.515796  13.328141
5                            9               92  52.485406  13.337745
6                           10               95  52.512532  13.326945
7                           11               98  52.509243  13.326963
8                           12              100  52.512791  13.389224
9                           15              135  52.429987  13.529880
10                          16              153  52.515649  13.401151
11                          17              171  52.584304  13.393721
12                          18              180  52.474552  13.457486
13                          19              190  52.532390  13.383218
14                          20              194  52.523578  13.342548
15                          21              201  52.520007  13.404954
16                          24              215  52.537567  13.606320
17                          25              222  52.558034  13.439384
18                          26              240  52.516584  13.403371
19                          28              276  52.500166  13.292532
20                          29              303  52.488459  13.533344
21                          30              304  52.515146  13.397365
22                          32              312  52.520007  13.404954
23                          33              313  52.488459  13.533344
24                          34              315  52.544653  13.352809
25                          35              316  52.423268  13.261658
26                          36              329  52.520007  13.404954
27                          37              330  52.469383  13.311426
28                          38              332  52.438743  13.328609
29                          39              338  52.435780  13.537809
30                          40              341  52.497665  13.440150
31                          41              343  52.505199  13.378054
32                          42              345  52.515796  13.328141
33                          43              346  52.520007  13.404954
34                          44              349  52.506407  13.365078
35                          45              359  52.505167  13.213509

   postcode                neighborhood  AGS_Code
0     14195         Steglitz-Zehlendorf  11000006
1     10117                       Mitte  11000001
2     10623  Charlottenburg-Wilmersdorf  11000004
3     14197  Charlottenburg-Wilmersdorf  11000004
4     10587  Charlottenburg-Wilmersdorf  11000004
5     10825        Tempelhof-Schöneberg  11000007
6     10623  Charlottenburg-Wilmersdorf  11000004
7     10623  Charlottenburg-Wilmersdorf  11000004
8     10117                       Mitte  11000001
9     12489            Treptow-Köpenick  11000009
10    10178                       Mitte  11000001
11    13156                      Pankow  11000003
12    12059                    Neukölln  11000008
13    10115                       Mitte  11000001
14    10555                       Mitte  11000001
15      nan                       Mitte  11000001
16    12627         Marzahn-Hellersdorf  11000010
17    13086                      Pankow  11000003
18    10178                       Mitte  11000001
19    10711  Charlottenburg-Wilmersdorf  11000004
20    10318                 Lichtenberg  11000011
21    10117                       Mitte  11000001
22      nan                       Mitte  11000001
23    10318                 Lichtenberg  11000011
24    13353                       Mitte  11000001
25    14167         Steglitz-Zehlendorf  11000006
26      nan                       Mitte  11000001
27    14197  Charlottenburg-Wilmersdorf  11000004
28    12247         Steglitz-Zehlendorf  11000006
29    12489            Treptow-Köpenick  11000009
30    10997    Friedrichshain-Kreuzberg  11000002
31    10963    Friedrichshain-Kreuzberg  11000002
32    10587  Charlottenburg-Wilmersdorf  11000004
33      nan                       Mitte  11000001
34    10785                       Mitte  11000001
35    14055  Charlottenburg-Wilmersdorf  11000004